import {Geist, Geist_Mono} from "next/font/google";
import "./globals.scss";
import 'bootstrap/dist/css/bootstrap.min.css';
import {getServerSession} from "next-auth";
import {authOptions} from "@/lib/auth";
import SessionProvider from "@/providers/page";
import {
  Button,
  Navbar,
  NavbarBrand,
  NavbarCollapse,
  NavbarText
} from "react-bootstrap";
import {PiSignOut} from "react-icons/pi";
import {SignOutBtn} from "@/components/signOutBtn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}) {
  const session = await getServerSession(authOptions);
  const {user = {}} = session || {user: {}};
  return (
    <html lang="en">
    <body data-bs-theme="dark"
          className={`${geistSans.variable} ${geistMono.variable} rootContainer`}>
    <SessionProvider session={session}>
      <Navbar className="rootNavbar">
        <NavbarBrand href={"/"}>Parlament parlamentu</NavbarBrand>
        <NavbarCollapse className="justify-content-end">
          <NavbarText>
            Zalogowano jako: {`${user?.name} ${user?.surname}`}
          </NavbarText>
          <SignOutBtn></SignOutBtn>
        </NavbarCollapse>
        <div className={"navbarSpacer"}></div>
      </Navbar>
      <div className={"contentContainer"}>
        {children}
      </div>
    </SessionProvider>
    </body>
    </html>
  );
}
